
# We are using cargo-bundle to create an app bundle under `target/release/bundle`
cargo bundle --release

# We replace the `Info.plist` file with a custom one which specifies that all
# file types are supported by this app. See CFBundleDocumentTypes.
# In a production environment this file should be automatically generated by
# either a cargo build script or by some other kind of script.
cp -r ./bundle-extra/Contents target/release/bundle/osx/winit_open.app
